[phases.setup]
nixPkgs = ["nodejs_20","pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build", "pnpm verify:dist"]

[start]
cmd = "pnpm --filter @tsc/api start:prod"