export type {
  AutomationEvaluatePayload,
  AutomationEvaluateResultItem,
  AutomationRuleDto,
  AutomationRunDto,
  AutomationStepRecord,
  AutomationTriggerResult,
  AutomationWorkflowType,
  ArtistHealthPayload,
  CityIntelligencePayload,
  CityRecommendationsPayload,
  CommandCenterArtistAtRisk,
  CommandCenterCityHeat,
  CommandCenterCommunityGrowth,
  CommandCenterForecast,
  CommandCenterOpportunity,
  CommandCenterPayload,
  CommandCenterV3Audience,
  CommandCenterV3Deals,
  CommandCenterV3Payload,
  CommandCenterV4Payload,
  CommunityIntelligencePayload,
  EcosystemGraphPayload,
  ExecutiveAggregatePayload,
  GoalDashboardEntry,
  GoalDashboardEntity,
  GoalDashboardPayload,
  GoalDto,
  IntelligenceActionResult,
  IntelligenceFanScoresPayload as FanScoresPayload,
  IntelligenceGoal,
  OpportunityHeat,
  OpportunityScoreItem,
  OpportunityScoresPayload,
  ParticipationDashboardPayload,
  ParticipationTopContributor,
  RecommendationListPayload,
  RiskAlert,
  FanSegmentMember,
  FanSegmentsPayload,
  SuggestedOpportunity,
} from '@tsc/types/intelligence';

export type {
  CommandCenterV4AudienceKpis,
  CommandCenterV5ActionableInsight,
  CommandCenterV5Payload,
  CommandCenterV5WorkflowBlock,
} from '@tsc/types';
