export {
  CollaborationTypeSchema,
  CollaborationStatusSchema,
  CollaborationApplicationStatusSchema,
  CollaborationBrowseQuerySchema,
  CollaborationCreateSchema,
  CollaborationUpdateSchema,
  CollaborationApplySchema,
  CollaborationApplicationUpdateSchema,
  type CollaborationBrowseQuery,
  type CollaborationCreateInput,
  type CollaborationUpdateInput,
  type CollaborationApplyInput,
  type CollaborationApplicationUpdateInput,
} from '@tsc/contracts/collaboration';
