/**
 * Whitelist for Admin Script Runner (/admin/scripts).
 * Only listed entries appear in the UI — not every file in server/scripts/.
 *
 * safety: safe (read-only / local checks) | caution (writes local or heavy) | danger (prod / destructive)
 */
module.exports = [
  // —— Dev & infra ——
  {
    id: 'preflight-env',
    fileName: 'preflightEnv.js',
    title: 'Preflight Environment',
    description: 'Validates required env vars before dev or deploy.',
    category: 'Dev & infra',
    safety: 'safe',
    args: [],
  },
  {
    id: 'list-backups',
    fileName: 'listBackups.js',
    title: 'List GridFS Backups',
    description: 'Lists available MongoDB backup snapshots in GridFS.',
    category: 'Dev & infra',
    safety: 'safe',
    args: [],
  },
  {
    id: 'generate-er',
    fileName: 'generateER.js',
    title: 'Generate ER Diagram Data',
    description: 'Builds entity-relationship reference output from models.',
    category: 'Dev & infra',
    safety: 'safe',
    args: [],
  },
  {
    id: 'test-notifications',
    fileName: 'testNotifications.js',
    title: 'Test Push Notifications',
    description: 'Smoke test for web push delivery paths.',
    category: 'Dev & infra',
    safety: 'caution',
    args: [],
  },
  {
    id: 'test-realtime',
    fileName: 'testRealtime.js',
    title: 'Test Realtime (Socket)',
    description: 'Socket.IO connectivity smoke test.',
    category: 'Dev & infra',
    safety: 'caution',
    args: [],
  },

  // —— Backup & cron ——
  {
    id: 'backup-daily',
    fileName: 'runDailyBackup.js',
    title: 'Run Daily Backup',
    description: 'Same job as Render cron — snapshots DB to GridFS.',
    category: 'Backup & cron',
    safety: 'caution',
    args: [],
  },
  {
    id: 'backup-test',
    fileName: 'testBackupNow.js',
    title: 'Test Backup Now',
    description: 'Manual backup run for verification.',
    category: 'Backup & cron',
    safety: 'caution',
    args: [],
  },
  {
    id: 'subscription-reminders',
    fileName: 'runSubscriptionReminders.js',
    title: 'Subscription Reminders',
    description: 'Sends due-date subscription notifications (cron job).',
    category: 'Backup & cron',
    safety: 'caution',
    args: [],
  },

  // —— QA ——
  {
    id: 'qa-audit',
    fileName: 'qaAuditReport.js',
    title: 'QA Audit Report (Local)',
    description: 'Read-only report of QA/test artifacts in local DB.',
    category: 'QA',
    safety: 'safe',
    args: [],
  },
  {
    id: 'qa-audit-prod',
    fileName: 'qaAuditReport.js',
    title: 'QA Audit Report (Production)',
    description: 'Read-only QA artifact report against production DB.',
    category: 'QA',
    safety: 'danger',
    args: ['--prod'],
  },
  {
    id: 'qa-verify-cleanup',
    fileName: 'verifyQaCleanup.js',
    title: 'Verify QA Cleanup',
    description: 'Checks that QA purge removed expected test data.',
    category: 'QA',
    safety: 'safe',
    args: [],
  },
  {
    id: 'qa-cleanup',
    fileName: 'qaFullCleanup.js',
    title: 'QA Full Cleanup (Local)',
    description: 'Removes QA test users, tasks, and related artifacts from local DB.',
    category: 'QA',
    safety: 'caution',
    args: [],
  },
  {
    id: 'qa-cleanup-prod',
    fileName: 'qaFullCleanup.js',
    title: 'QA Full Cleanup (Production)',
    description: 'Purges QA artifacts from production — use only after audit.',
    category: 'QA',
    safety: 'danger',
    args: ['--prod'],
  },
  {
    id: 'qa-scan',
    fileName: 'runQAScan.js',
    title: 'Run QA Scan',
    description: 'Runs automated QA test scan via QATestingService.',
    category: 'QA',
    safety: 'caution',
    args: [],
  },
  {
    id: 'qa-trigger-http',
    fileName: 'triggerQaHttp.js',
    title: 'Trigger QA HTTP Suite',
    description: 'HTTP-triggered QA integration subset.',
    category: 'QA',
    safety: 'caution',
    args: [],
  },

  // —— Data repair (read-only first) ——
  {
    id: 'audit-lead-phones',
    fileName: 'auditLeadPhones.js',
    title: 'Audit Lead Phones',
    description: 'Read-only scan for corrupt or invalid lead phone numbers.',
    category: 'Data repair',
    safety: 'safe',
    args: [],
  },
  {
    id: 'scan-corrupt-phones',
    fileName: 'scanCorruptPhones.js',
    title: 'Scan Corrupt Phones',
    description: 'Lists leads with phone values that fail validation rules.',
    category: 'Data repair',
    safety: 'safe',
    args: [],
  },
  {
    id: 'repair-phones-local',
    fileName: 'repairCorruptPhones.js',
    title: 'Repair Lead Phones (Local)',
    description: 'Dedupes and fixes corrupt lead phones in local DB.',
    category: 'Data repair',
    safety: 'caution',
    args: ['--local'],
  },
  {
    id: 'repair-phones-prod',
    fileName: 'repairCorruptPhones.js',
    title: 'Repair Lead Phones (Production)',
    description: 'Repairs corrupt lead phones in production — backup first.',
    category: 'Data repair',
    safety: 'danger',
    args: ['--prod'],
  },
  {
    id: 'normalize-person-dry',
    fileName: 'normalizePersonData.js',
    title: 'Normalize Person Data (Dry Run)',
    description: 'Preview person field backfill across CRM — no writes.',
    category: 'Data repair',
    safety: 'safe',
    args: ['--dry-run'],
  },
  {
    id: 'check-attendance-dupes',
    fileName: 'checkAttendanceDuplicates.js',
    title: 'Check Attendance Duplicates',
    description: 'Finds duplicate attendance rows for review.',
    category: 'Data repair',
    safety: 'safe',
    args: [],
  },
  {
    id: 'diagnose-gamification',
    fileName: 'diagnoseGamification.js',
    title: 'Diagnose Gamification',
    description: 'Inspects XP, levels, and mission config consistency.',
    category: 'Data repair',
    safety: 'caution',
    args: [],
  },
  {
    id: 'seed-departments',
    fileName: 'seedDepartmentsAndTaskTypes.js',
    title: 'Seed Departments & Task Types',
    description: 'Seeds department presets and mines task types (local/fresh env).',
    category: 'Data repair',
    safety: 'caution',
    args: [],
  },

  // —— Database sync ——
  {
    id: 'compare-datahub',
    fileName: 'compareDataHubDbs.js',
    title: 'Compare Data Hub (Local vs Prod)',
    description: 'Collection count diff for Data Hub and calendar.',
    category: 'Database sync',
    safety: 'safe',
    args: [],
  },
  {
    id: 'sync-prod-to-local',
    fileName: 'syncProdToLocal.js',
    title: 'Sync Production → Local',
    description: 'Replaces ALL local collections with production snapshot. Requires --yes.',
    category: 'Database sync',
    safety: 'danger',
    args: ['--yes'],
  },
  {
    id: 'reconcile-datahub-local',
    fileName: 'reconcileDataHub.js',
    title: 'Reconcile Data Hub (Local)',
    description: 'Incremental Contact hub merge on local DB.',
    category: 'Database sync',
    safety: 'caution',
    args: [],
  },
  {
    id: 'reconcile-datahub-prod',
    fileName: 'reconcileDataHub.js',
    title: 'Reconcile Data Hub (Production Full)',
    description: 'Full Data Hub reconcile on production — high impact.',
    category: 'Database sync',
    safety: 'danger',
    args: ['--prod', '--full'],
  },

  // —— Finance ——
  {
    id: 'import-finance',
    fileName: 'importInvoices.js',
    title: 'Import Finance Invoices',
    description: 'Imports Basecamp download folders into finance docs (skip OCR).',
    category: 'Finance',
    safety: 'caution',
    args: ['--skip-ocr'],
  },
  {
    id: 'reparse-finance-ocr',
    fileName: 'reparseFinanceOcr.js',
    title: 'Reparse Finance OCR',
    description: 'Re-runs OCR parsing on existing finance documents.',
    category: 'Finance',
    safety: 'caution',
    args: [],
  },

  // —— Audits (needs API on :5000 for some) ——
  {
    id: 'user-flow-audit',
    fileName: 'userFlowAudit.js',
    title: 'User Flow Audit',
    description: 'Read-only user-flow consistency report.',
    category: 'Audits',
    safety: 'safe',
    args: [],
  },
  {
    id: 'full-project-audit',
    fileName: 'fullProjectAudit.js',
    title: 'Full Project Audit',
    description: 'Frontend build + API smoke + RBAC. Requires local API on port 5000.',
    category: 'Audits',
    safety: 'caution',
    args: [],
  },
];
