/**
 * Platform registry — add new providers here without touching UI controllers.
 */
const INTEGRATIONS = [
  // Music
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'music',
    hasAnalytics: true,
    hasOAuth: true,
    connectMethod: 'oauth',
    colorClass: 'emerald',
    icon: 'spotify',
    authConnectPath: '/api/auth/connect/spotify',
    metricsKeys: ['followers', 'popularity', 'monthlyListeners'],
    followerField: 'followers',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'rose',
    icon: 'apple-music',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'jiosaavn',
    name: 'JioSaavn',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'green',
    icon: 'jiosaavn',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'gaana',
    name: 'Gaana',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'orange',
    icon: 'gaana',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'wynk',
    name: 'Wynk',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'red',
    icon: 'wynk',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'amazon-music',
    name: 'Amazon Music',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'cyan',
    icon: 'amazon-music',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'manual',
    colorClass: 'orange',
    icon: 'soundcloud',
    authConnectPath: null,
    metricsKeys: ['followers'],
    followerField: 'followers',
  },
  {
    id: 'audiomack',
    name: 'Audiomack',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'amber',
    icon: 'audiomack',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'beatport',
    name: 'Beatport',
    category: 'music',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'lime',
    icon: 'beatport',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  // Social
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'social',
    hasAnalytics: true,
    hasOAuth: true,
    connectMethod: 'oauth',
    colorClass: 'rose',
    icon: 'youtube',
    authConnectPath: '/api/auth/connect/youtube',
    metricsKeys: ['subscribers', 'views', 'videoCount'],
    followerField: 'subscribers',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'social',
    hasAnalytics: true,
    hasOAuth: true,
    connectMethod: 'oauth',
    colorClass: 'pink',
    icon: 'instagram',
    authConnectPath: '/api/auth/connect/instagram',
    metricsKeys: ['followers', 'engagementRate', 'reach'],
    followerField: 'followers',
    parentProvider: 'meta',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'social',
    hasAnalytics: true,
    hasOAuth: false,
    connectMethod: 'manual',
    colorClass: 'blue',
    icon: 'facebook',
    authConnectPath: null,
    metricsKeys: ['followers', 'likes', 'reach'],
    followerField: 'followers',
    parentProvider: 'meta',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'manual',
    colorClass: 'slate',
    icon: 'tiktok',
    authConnectPath: null,
    metricsKeys: ['followers', 'views'],
    followerField: 'followers',
  },
  {
    id: 'threads',
    name: 'Threads',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'zinc',
    icon: 'threads',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'x',
    name: 'X',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'neutral',
    icon: 'x',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'sky',
    icon: 'linkedin',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'yellow',
    icon: 'snapchat',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'manual',
    colorClass: 'indigo',
    icon: 'discord',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'social',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'manual',
    colorClass: 'sky',
    icon: 'telegram',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  // Creator
  {
    id: 'patreon',
    name: 'Patreon',
    category: 'creator',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'orange',
    icon: 'patreon',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'creator',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'purple',
    icon: 'twitch',
    authConnectPath: null,
    metricsKeys: ['followers', 'views'],
    followerField: 'followers',
  },
  {
    id: 'substack',
    name: 'Substack',
    category: 'creator',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'orange',
    icon: 'substack',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  // Commerce
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'commerce',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'green',
    icon: 'shopify',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'commerce',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'purple',
    icon: 'woocommerce',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  // Ticketing
  {
    id: 'bookmyshow',
    name: 'BookMyShow',
    category: 'ticketing',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'red',
    icon: 'bookmyshow',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'insider',
    name: 'Insider',
    category: 'ticketing',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'pink',
    icon: 'insider',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
  {
    id: 'skillbox',
    name: 'Skillbox',
    category: 'ticketing',
    hasAnalytics: false,
    hasOAuth: false,
    connectMethod: 'coming_soon',
    colorClass: 'violet',
    icon: 'skillbox',
    authConnectPath: null,
    metricsKeys: [],
    followerField: null,
  },
];

const INTEGRATION_CATEGORIES = [
  { id: 'music', label: 'Music' },
  { id: 'social', label: 'Social' },
  { id: 'creator', label: 'Creator' },
  { id: 'commerce', label: 'Commerce' },
  { id: 'ticketing', label: 'Ticketing' },
];

const byId = (id) => INTEGRATIONS.find((p) => p.id === id);

const analyticsProviders = () => INTEGRATIONS.filter((p) => p.hasAnalytics);

const byCategory = (category) => INTEGRATIONS.filter((p) => p.category === category);

module.exports = {
  INTEGRATIONS,
  INTEGRATION_CATEGORIES,
  byId,
  byCategory,
  analyticsProviders,
};
