/** Random humorous loading copy — no generic "Loading..." in the app */

const PHRASES = [
  'Building Dominos using pizza',
  'Overhearing the neighbours',
  'Deploying Stealth Drones',
  'Making Dinner Arrangements',
  'Customizing Dashboard',
  'Optimizing your workflow',
  'Buying a Red Sofa',
  'Composing Elements',
  'Learning Sa Re Ga Ma',
  'Memorizing all digits of PI',
  '*Elevator Music Playing*',
  'Arguing with the printer',
  'Bribing the Wi-Fi router',
  'Calibrating office plants',
  'Charging the chaos battery',
  'Convincing spreadsheets to behave',
  'Counting backwards from infinity',
  'Debugging the coffee machine',
  'Dusting cloud servers',
  'Explaining memes to management',
  'Feeding the hamsters in the server room',
  'Finding where the meeting link went',
  'Fluffing the cloud pillows',
  'Herding notification cats',
  'Hiding from Monday',
  'Inflating idea balloons',
  'Installing more RAM in reality',
  'Ironing the timeline',
  'Listening to hold music professionally',
  'Locating the any key',
  'Negotiating with deadlines',
  'Organizing chaos alphabetically',
  'Painting the fourth wall',
  'Persuading pixels to align',
  'Polishing the loading spinner',
  'Rebooting enthusiasm',
  'Recalibrating the vibe',
  'Recycling old excuses',
  'Reheating leftover motivation',
  'Removing invisible ink from reports',
  'Renaming untitled_final_FINAL_v2',
  'Replacing batteries in the flux capacitor',
  'Reticulating splines',
  'Rewinding the awkward silence',
  'Sanding rough edges off the day',
  'Scheduling unscheduled meetings',
  'Sharpening digital pencils',
  'Shuffling deck chairs elegantly',
  'Smoothing spreadsheet wrinkles',
  'Sorting inbox by vibes',
  'Spinning up good intentions',
  'Staging a productivity musical',
  'Stocking the snack cache',
  'Stretching the bandwidth',
  'Summoning the right tab',
  'Synchronizing watch parties',
  'Teaching AI to enjoy chai',
  'Tidying virtual desk drawers',
  'Training pigeons for internal mail',
  'Translating engineer to human',
  'Trimming notification hedges',
  'Tuning the office theremin',
  'Turning it off and on again spiritually',
  'Untangling headphone cables in the cloud',
  'Upgrading patience to v2',
  'Waiting for the other cursor',
  'Watering the roadmap garden',
  'Whispering to databases',
  'Warming up the punchlines',
  'Writing passive-aggressive reminders',
  'Yoga for your columns',
  'Zipping the universe quietly',
  'Adopting orphaned tasks',
  'Aligning chakras and columns',
  'Appeasing the spreadsheet gods',
  'Asking the magic 8-ball for ETA',
  'Balancing rocks on the backlog',
  'Befriending a loading bar',
  'Borrowing time from tomorrow',
  'Brewing stronger insights',
  'Building a blanket fort of tabs',
  'Cataloguing mysterious cables',
  'Chasing runaway cursors',
  'Checking if it is Friday yet',
  'Cloning the good idea',
  'Coaching shy attachments',
  'Collecting rubber ducks for debugging',
  'Composing hold music lyrics',
  'Consulting the office oracle',
  'Converting caffeine to code',
  'Crafting artisanal metadata',
  'Crocheting a safety net',
  'Cross-stitching the org chart',
  'Cultivating polite notifications',
  'Curating awkward small talk',
  'Decoding manager speak',
  'Defrosting frozen tabs',
  'Deleting duplicate duplicates',
  'Diplomacy with the calendar',
  'Discovering new ways to procrastinate productively',
  'Distracting the spin wheel of doom',
  'Doodling flowcharts in margins',
  'Downloading more creativity',
  'Dusting off ancient shortcuts',
  'Editing reality for clarity',
  'Encouraging shy pixels',
  'Enrolling tabs in etiquette school',
  'Escaping the reply-all vortex',
  'Estimating wildly but confidently',
  'Exorcising ghost notifications',
  'Expanding the snack horizon',
  'Fact-checking the vibe',
  'Filing paperwork for fun',
  'Finding Nemo in the shared drive',
  'Fixing things that were not broken yet',
  'Flipping tables then unflipping them',
  'Forging legendary to-do lists',
  'Freeing trapped potential',
  'Frothing data lightly',
  'Gamifying the waiting',
  'Gathering plot threads',
  'Generating plausible deniability',
  'Gently bonking the server',
  'Ghostwriting your status update',
  'Gift-wrapping deliverables',
  'Googling how to Google',
  'Grazing in the notification meadow',
  'Greasing the gears of teamwork',
  'Growing ideas in petri dishes',
  'Hacking the planet politely',
  'Hanging lights on the data tree',
  'Hatching weekend plans',
  'Heating up cold takes',
  'Herding cats into a Kanban board',
  'Hiding easter eggs in reports',
  'High-fiving the algorithm',
  'Hoarding browser tabs responsibly',
  'Holding space for buffers',
  'Hosting a pity party for bugs',
  'Hunting typos with a net',
  'Hypnotizing the progress bar',
  'Importing confidence',
  'Inventing a new holiday',
  'Inviting chaos to tea',
  'Juggling priorities and oranges',
  'Karate-chopping latency',
  'Kicking the tires on reality',
  'Knitting connections',
  'Labeling the label maker',
  'Launching paper airplanes of hope',
  'Leashing the scope creep',
  'Lecturing the loading icon',
  'Licking stamps for e-mail',
  'Linking the unlinked',
  'Listening to plant gossip',
  'Loading courage module',
  'Lobbying for lunch',
  'Lockpicking the afternoon slump',
  'Lubricating social gears',
  'Macraméing project timelines',
  'Magnetizing sticky notes',
  'Manifesting merge conflicts away',
  'Mapping the snack terrain',
  'Marinating thoughts',
  'Measuring twice cutting once emotionally',
  'Meditating on metadata',
  'Melting stress popsicles',
  'Merging parallel universes',
  'Mild panic in 4K',
  'Mining for silver linings',
  'Mixing the perfect playlist for spreadsheets',
  'Moisturizing dry humor',
  'Molding clay into KPIs',
  'Murmuring sweet nothings to APIs',
  'Myth-busting Monday',
  'Napping with eyes open',
  'Narrating the loading screen',
  'Negotiating snack treaty',
  'Noodling on strategy',
  'Normalizing weird data',
  'Notifying the notifications',
  'Nurturing baby ideas',
  'Objecting your honor emotionally',
  'Oil painting the dashboard',
  'Opening a wormhole to inbox zero',
  'Optimizing nap schedules',
  'Orchestrating keyboard symphonies',
  'Outsmarting the office chair',
  'Packaging chaos neatly',
  'Paging Dr. Motivation',
  'Painting numbers happier',
  'Pampering the cache',
  'Parachuting new features',
  'Parking the thought bus',
  'Parsing small talk',
  'Partnering with probability',
  'Passing the aux cord of destiny',
  'Patting servers on the back',
  'Peeling onion layers of tasks',
  'Perusing the cosmic backlog',
  'Petting the office dog remotely',
  'Photoshopping reality slightly',
  'Picking the perfect emoji',
  'Piloting a desk submarine',
  'Ping ponging ideas',
  'Placing dominoes carefully',
  'Planning the five-year lunch',
  'Planting seeds of spreadsheets',
  'Playing chess with deadlines',
  'Plotting world domination mildly',
  'Plucking low-hanging fruit',
  'Pocketing stray thoughts',
  'Polishing the brass tacks',
  'Popping bubble wrap virtually',
  'Practicing dramatic entrances',
  'Preheating the brainstorm oven',
  'Preparing a TED talk for squirrels',
  'Pretending to understand the chart',
  'Printing invisible documents',
  'Procrastinating with purpose',
  'Proofreading the universe',
  'Puppeteering productivity',
  'Puzzling the pieces',
  'Quantum leaping afternoons',
  'Quarantining bad ideas',
  'Questioning everything politely',
  'Queueing jazz hands',
  'Quilting reports together',
  'Raising eyebrows strategically',
  'Raking leaves in the cloud',
  'Rallying the spreadsheet militia',
  'Ransoming time from meetings',
  'Recharging sarcasm reserves',
  'Recording bird songs for focus',
  'Recruiting allies for inbox zero',
  'Redesigning the wheel slightly rounder',
  'Rehearsing acceptance speeches',
  'Reindexing the fun database',
  'Relaxing aggressively',
  'Remixing the agenda',
  'Removing skeletons from closets',
  'Renting more attention span',
  'Reorganizing the junk drawer of ideas',
  'Repairing the space-time spreadsheet',
  'Replacing chaos with slightly less chaos',
  'Requesting divine alignment',
  'Rescuing lost attachments',
  'Restocking the meme vault',
  'Reticulating coffee',
  'Returning borrowed pens',
  'Reviewing life choices cheerfully',
  'Reviving fossilized drafts',
  'Rewiring gut feelings',
  'Rinsing repeat offenders',
  'Road-testing patience',
  'Rolling out the red spreadsheet',
  'Romancing the data',
  'Rotating the responsibility wheel',
  'Rounding up wild numbers',
  'Rubber duck tribunal in session',
  'Running diagnostics on vibes',
  'Salting the slug trail of bugs',
  'Sanitizing bad puns',
  'Satiating curiosity gremlins',
  'Sautéing insights',
  'Saving the world before snack',
  'Scaling Mount Inbox',
  'Scouting for typos',
  'Sculpting timelines',
  'Sealing time capsules of notes',
  'Searching for the other sock',
  'Seeding random kindness',
  'Segmenting the nonsense',
  'Selling ice to penguins ethically',
  'Sending thoughts and prayers to Wi-Fi',
  'Serializing cereal',
  'Setting phasers to organize',
  'Shaking the magic 8-ball again',
  'Sharpening wit and pencils',
  'Shepherding pixels home',
  'Shoveling snow from yesterday',
  'Shrinking the elephant in the room',
  'Signing peace treaty with spam',
  'Simmering stakeholder soup',
  'Sketching escape routes',
  'Skimming the surface expertly',
  'Slaloming through policies',
  'Slaying dragon processes',
  'Slicing bread with spreadsheets',
  'Sliding into data like DM',
  'Smuggling joy into forms',
  'Snacking on insights',
  'Snoozing alarms philosophically',
  'Soapboxing to spreadsheets',
  'Socializing introverted files',
  'Softening harsh tables',
  'Solidifying jello plans',
  'Soothing angry cells',
  'Spacing out productively',
  'Spackling plot holes',
  'Sparkling mental inventory',
  'Spearheading the snack committee',
  'Speed-running small talk',
  'Spelunking the archive',
  'Spicing up vanilla reports',
  'Spinning plates of priorities',
  'Splashing color on gray days',
  'Spoon-feeding the algorithm',
  'Spreading butter on bandwidth',
  'Spring-cleaning tabs',
  'Sprinkling fairy dust on forms',
  'Squashing bugs with compassion',
  'Squeezing lemons into insights',
  'Stabilizing wobbly plans',
  'Stacking blocks of focus',
  'Stalking the perfect GIF',
  'Stampeding toward clarity',
  'Staring meaningfully at charts',
  'Steaming milk for mocha reports',
  'Steering the conversation ship',
  'Stepping over LEGO ideas',
  'Stitching narratives together',
  'Stocking hope shelves',
  'Stomping grapes of wrath gently',
  'Storyboarding your success',
  'Straining the news soup',
  'Strategizing snack acquisition',
  'Stretching the truth to fit cells',
  'Stroking beard thoughtfully',
  'Structuring unstructured chaos',
  'Stuffing envelopes with dreams',
  'Subduing feral formulas',
  'Subletting brain space',
  'Submarining through email',
  'Summoning autumn vibes',
  'Sunsetting bad habits',
  'Superglueing attention span',
  'Supplying dramatic tension',
  'Surfing the chaos wave',
  'Surveying the snack landscape',
  'Surviving plot twists',
  'Swaddling newborn projects',
  'Swapping batteries in motivation',
  'Sweeping bugs under rug labeled fixed',
  'Sweet-talking the firewall',
  'Swimming through paperwork',
  'Swinging the pendulum of focus',
  'Switching hats rapidly',
  'Synchronizing snack breaks',
  'Synergizing the obvious',
  'Tabulating happiness index',
  'Taming wild columns',
  'Taping the universe together',
  'Tasting data for quality',
  'Teaching old dogs new shortcuts',
  'Telepathically syncing teams',
  'Tenderizing tough feedback',
  'Testing patience limits',
  'Thanking the bus driver of fate',
  'Theorizing about lunch',
  'Thermostating tempers',
  'Thrashing politely',
  'Tickling the funny bone of logic',
  'Tidying quantum clutter',
  'Tightening loose ends',
  'Tiptoeing around scope creep',
  'Toast-testing the morning',
  'Toasting marshmallows of ideas',
  'Toddler-proofing the plan',
  'Toggling reality settings',
  'Toning mental muscles',
  'Tooling up for triumph',
  'Topiary-trimming the org chart',
  'Towing the deadline barge',
  'Tracing spaghetti diagrams',
  'Trading stocks of motivation',
  'Training laser focus',
  'Transmuting lead into gold KPIs',
  'Transporting snacks dimensionally',
  'Trapping lightning in a pivot table',
  'Traveling at the speed of staff meeting',
  'Treating yo self to data',
  'Trimming the hedges of bureaucracy',
  'Triangulating blame gently',
  'Troubleshooting the universe',
  'Truffle-hunting insights',
  'Tucking in stray threads',
  'Tuning the chaos orchestra',
  'Turning down the drama thermostat',
  'Tutoring beginners luck',
  'Twirling mustaches thoughtfully',
  'Twisting balloons into workflows',
  'Uncrumpling the timeline',
  'Undercoating reality',
  'Unfolding origami plans',
  'Unicycling through policies',
  'Unknotting meeting notes',
  'Unlocking achievement chests',
  'Unmuting the inner monologue',
  'Unpacking invisible luggage',
  'Untwisting pretzel logic',
  'Upcycling old excuses',
  'Upgrading the snack firmware',
  'Uploading soul to cloud',
  'Ushering cats into rows',
  'Vacuuming digital dust',
  'Validating vibes scientifically',
  'Varnishing the truth lightly',
  'Vaulting over hurdles',
  'Vectoring enthusiasm',
  'Ventriloquizing spreadsheets',
  'Vibing with the database',
  'Vindicating stubborn hunches',
  'Visiting the idea thrift store',
  'Vitalizing stale coffee thoughts',
  'Vlogging the loading experience',
  'Volleyballing decisions',
  'Volunteering reality for tests',
  'Voodoo debugging gently',
  'Waddling toward greatness',
  'Waging war on clutter',
  'Waiting for stars to align',
  'Walking the dog of duty',
  'Warming up the pun engine',
  'Warning charts about surprises',
  'Washing brain windows',
  'Watching paint dry in HD',
  'Waterboarding spreadsheets with love',
  'Wave-function collapsing choices',
  'Weaving fate from threads',
  'Wedding cake tasting for metrics',
  'Whacking moles of chaos',
  'Wheeling in more chairs',
  'Whispering secrets to SQL',
  'Whitewashing worries',
  'Wiggling loose bolts',
  'Winning bingo of buzzwords',
  'Wiring synapses to Wi-Fi',
  'Wishing on office supplies',
  'Woking the data pan',
  'Wondering where time went',
  'Woodworking the framework',
  'Woolgathering strategically',
  'Wordsmithing notifications',
  'Workshopping the workshop',
  'World-building your dashboard',
  'Wrestling alligators of admin',
  'Wrangling runaway fonts',
  'Wrapping gifts of context',
  'Wringing water from clouds',
  'Writing fan fiction for KPIs',
  'Xeroxing charisma',
  'Yanking chains of dependency',
  'Yawning in stereo',
  'Yeeting bugs into void',
  'Yodeling for tech support',
  'Yoga for your pivot tables',
  'Zesting the data lime',
  'Zigzagging through approvals',
  'Zipping up loose ends',
  'Zoning out productively',
  'Zooming with enthusiasm',
];

const LOADING_PHRASE_COUNT = PHRASES.length;

export function pickRandomLoadingPhrase() {
  return PHRASES[Math.floor(Math.random() * PHRASES.length)];
}
