/** Vite MPA entry points — path key → HTML file relative to apps/website */
export const ROUTES = {
  main: 'index.html',
  about: 'about/index.html',
  stories: 'stories/index.html',
  films: 'films/index.html',
  collab: 'collab/index.html',
  insights: 'insights/index.html',
  'insights-artist-release-playbook': 'insights/artist-release-playbook/index.html',
  'insights-breathing-vocal-texture': 'insights/breathing-vocal-texture/index.html',
  'insights-daily-riyaaz-routine': 'insights/daily-riyaaz-routine/index.html',
  artists: 'artists/index.html',
  harshadduhita: 'harshadduhita/index.html',
  yugm: 'yugm/index.html',
  mohitshanker: 'mohitshanker/index.html',
  'book-a-call': 'book-a-call/index.html',
  query: 'query/index.html',
  'artist-path': 'artist-path/index.html',
  academy: 'academy/index.html',
  'academy-ambassador': 'academy/ambassador/index.html',
  'courses-composition': 'courses/composition-comprehensive/index.html',
  'courses-hindustani': 'courses/hindustani-classical/index.html',
  'courses-production': 'courses/music-production/index.html',
  'masterclass-sandesh': 'masterclass/sandesh-shandilya/index.html',
  'masterclass-prasad': 'masterclass/prasad-khaparde/index.html',
  classicalreview: 'classicalreview/index.html',
  'masterclass-review01': 'masterclass-review01/index.html',
  'masterclass-review02': 'masterclass-review02/index.html',
  'links-harshad': 'links/harshad-and-duhita/index.html',
  'links-yugm': 'links/yugm/index.html',
};

export const REDIRECTS = [
  { source: '/tscacademy', destination: '/academy', permanent: true },
  { source: '/tscacademy/ambassador', destination: '/academy/ambassador', permanent: true },
  { source: '/resources', destination: '/insights', permanent: true },
  { source: '/ip', destination: '/stories', permanent: true },
  { source: '/artist', destination: '/query', permanent: false },
  { source: '/contact', destination: '/about#contact', permanent: false },
];
